services:
  postgres:
    image: postgres:17
    container_name: creator_pg
    environment:
      POSTGRES_USER: spotify
      POSTGRES_PASSWORD: spotify
      POSTGRES_DB: creator_lab
    ports:
      - "55432:5432"
    volumes:
      - pgdata_creator_lab:/var/lib/postgresql/data

volumes:
  pgdata_creator_lab: